/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Healthz
         * @description Liveness: process is up. No dependency calls.
         */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readyz
         * @description Readiness: dependencies reachable. 503 (with body) when degraded.
         */
        get: operations["readyz_readyz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/invoices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Invoices
         * @description Filterable, server-side-paginated queue (Maria's list view, #28).
         */
        get: operations["list_invoices_v1_invoices_get"];
        put?: never;
        /**
         * Ingest Invoice
         * @description Accept a raw invoice document; returns the invoice + run identity.
         *
         *     Idempotency: a repeated ``Idempotency-Key`` replays the stored response
         *     without re-ingesting (the middleware attaches the key to request.state).
         *     A fresh (non-duplicate) acceptance schedules the processing graph as a
         *     background task — the run state is observable via the ledger/trace.
         */
        post: operations["ingest_invoice_v1_invoices_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/invoices/{invoice_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Invoice Detail
         * @description Full aggregate — invoice + extraction (confidences) + match deltas +
         *     policy findings + exception/triage + ledger summary (RBAC-filtered).
         */
        get: operations["invoice_detail_v1_invoices__invoice_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/invoices/email-webhook": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Email Webhook */
        post: operations["email_webhook_v1_invoices_email_webhook_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/exceptions/{exception_id}/decision": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Decide Exception
         * @description Record a human decision on an exception.
         *
         *     Four-eyes: APPROVE by the exception's assignee is rejected (409). A
         *     resolved exception replays the identical decision idempotently (200,
         *     ``X-Idempotent-Replay``) and rejects a conflicting one (409). Resuming
         *     actions continue the paused graph through HumanReview to Archive.
         */
        post: operations["decide_exception_v1_exceptions__exception_id__decision_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/runs/{run_id}/trace": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Run Trace
         * @description Ordered node timeline for one run — ledger events (one per node, plus
         *     retries/DLQ/decision extras) with the checkpointed node order.
         */
        get: operations["run_trace_v1_runs__run_id__trace_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/invoices/{invoice_id}/provenance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Invoice Provenance
         * @description Complete decision provenance — runs, exceptions, decisions, and the
         *     full ledger with version pins. Audit/platform roles only (ARCHITECTURE §5).
         */
        get: operations["invoice_provenance_v1_invoices__invoice_id__provenance_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_ingest_invoice_v1_invoices_post */
        Body_ingest_invoice_v1_invoices_post: {
            /** Upload */
            upload: string;
        };
        /**
         * DecisionAction
         * @enum {string}
         */
        DecisionAction: "APPROVE" | "RETURN_TO_VENDOR" | "ESCALATE";
        /** DecisionRequest */
        DecisionRequest: {
            action: components["schemas"]["DecisionAction"];
            /** Rationale */
            rationale: string;
            /** Reason Code */
            reason_code: string;
            /** Escalate To */
            escalate_to?: string | null;
        };
        /** DecisionResponse */
        DecisionResponse: {
            /** Decision Id */
            decision_id: number;
            /** Exception Id */
            exception_id: number;
            /** Invoice Id */
            invoice_id: number;
            action: components["schemas"]["DecisionAction"];
            /** Actor */
            actor: string;
            /** Reason Code */
            reason_code: string;
            /** Created At */
            created_at: string;
            /** Exception Status */
            exception_status: string;
            /** Graph Resumed */
            graph_resumed: boolean;
            /**
             * Idempotent Replay
             * @default false
             */
            idempotent_replay: boolean;
        };
        /** EmailAttachment */
        EmailAttachment: {
            /** Filename */
            filename: string;
            /** Content Type */
            content_type: string;
            /** Content B64 */
            content_b64: string;
        };
        /** EmailWebhookPayload */
        EmailWebhookPayload: {
            /** Message Id */
            message_id: string;
            /** Received At */
            received_at: string;
            attachment: components["schemas"]["EmailAttachment"];
        };
        /** ExtractionLineView */
        ExtractionLineView: {
            /** Line No */
            line_no: string;
            /** Description */
            description?: string | null;
            /** Qty */
            qty?: string | null;
            /** Uom */
            uom?: string | null;
            /** Unit Price */
            unit_price?: string | null;
            /** Tax Code */
            tax_code?: string | null;
            /** Line Total */
            line_total?: string | null;
        };
        /**
         * ExtractionView
         * @description Checkpointed extraction with per-field confidences (gate inputs).
         */
        ExtractionView: {
            /** Vendor Name */
            vendor_name?: string | null;
            /** Invoice Number */
            invoice_number?: string | null;
            /** Po Number */
            po_number?: string | null;
            /** Issue Date */
            issue_date?: string | null;
            /** Due Date */
            due_date?: string | null;
            /** Currency */
            currency?: string | null;
            /** Total Amount */
            total_amount?: string | null;
            /** Tax Total */
            tax_total?: string | null;
            /** Iban */
            iban?: string | null;
            /** Lines */
            lines?: components["schemas"]["ExtractionLineView"][];
            /** Confidences */
            confidences?: {
                [key: string]: number;
            };
            /** Min Confidence */
            min_confidence?: number | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * InvoiceAccepted
         * @description 201 response for POST /v1/invoices (new document accepted).
         */
        InvoiceAccepted: {
            /** Invoice Id */
            invoice_id: number;
            /** Run Id */
            run_id: number;
            /** Content Hash */
            content_hash: string;
            /**
             * Status
             * @default RECEIVED
             */
            status: string;
            /**
             * Duplicate
             * @default false
             */
            duplicate: boolean;
        };
        /**
         * InvoiceDetailAggregate
         * @description GET /v1/invoices/{id}: everything the review screens need, one call.
         */
        InvoiceDetailAggregate: {
            invoice: components["schemas"]["QueueItem"];
            /** Lines */
            lines?: components["schemas"]["ExtractionLineView"][];
            extraction?: components["schemas"]["ExtractionView"] | null;
            /** Validation */
            validation?: {
                [key: string]: unknown;
            }[];
            /** Match */
            match?: {
                [key: string]: unknown;
            } | null;
            /** Policy */
            policy?: {
                [key: string]: unknown;
            }[];
            /** Gate */
            gate?: {
                [key: string]: unknown;
            } | null;
            /** Exception */
            exception?: {
                [key: string]: unknown;
            } | null;
            ledger: components["schemas"]["LedgerSummary"];
            /**
             * State Available
             * @default true
             */
            state_available: boolean;
        };
        /** LedgerSummary */
        LedgerSummary: {
            /** Entry Count */
            entry_count: number;
            /** Last Entries */
            last_entries: components["schemas"]["LedgerSummaryEntry"][];
        };
        /** LedgerSummaryEntry */
        LedgerSummaryEntry: {
            /** Seq */
            seq: number;
            /** Actor Type */
            actor_type: string;
            /** Actor Id */
            actor_id: string | null;
            /** Event */
            event: string;
            /** Created At */
            created_at: string;
            /** Versions */
            versions?: {
                [key: string]: unknown;
            } | null;
            /** Policy Version */
            policy_version?: string | null;
            /** Prompt Template Version */
            prompt_template_version?: string | null;
        };
        /** ProvenanceDecision */
        ProvenanceDecision: {
            /** Decision Id */
            decision_id: number;
            /** Exception Id */
            exception_id: number;
            /** Actor User */
            actor_user: string;
            /** Action */
            action: string;
            /** Rationale */
            rationale: string;
            /** Reason Code */
            reason_code: string;
            /** Created At */
            created_at: string;
        };
        /** ProvenanceException */
        ProvenanceException: {
            /** Exception Id */
            exception_id: number;
            /** Run Id */
            run_id: number | null;
            /** Type */
            type: string;
            /** Severity */
            severity: string;
            /** Status */
            status: string;
            /** Evidence */
            evidence: {
                [key: string]: unknown;
            };
            /** Recommendation */
            recommendation: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * ProvenancePackage
         * @description GET /v1/invoices/{id}/provenance — every decision and the versions
         *     behind it; the export shape Priya's screen renders (README G3).
         */
        ProvenancePackage: {
            /** Invoice Id */
            invoice_id: number;
            /** Generated At */
            generated_at: string;
            /** Runs */
            runs: components["schemas"]["ProvenanceRun"][];
            /** Exceptions */
            exceptions: components["schemas"]["ProvenanceException"][];
            /** Decisions */
            decisions: components["schemas"]["ProvenanceDecision"][];
            /** Ledger */
            ledger: components["schemas"]["TraceEvent"][];
        };
        /** ProvenanceRun */
        ProvenanceRun: {
            /** Run Id */
            run_id: number;
            /** Graph Version */
            graph_version: string;
            /** Model Versions */
            model_versions: {
                [key: string]: unknown;
            };
            /** Route */
            route: string | null;
            /** Status */
            status: string;
            /** Confidence */
            confidence: number | null;
            /** Started At */
            started_at: string;
            /** Finished At */
            finished_at: string | null;
        };
        /** QueueExceptionSummary */
        QueueExceptionSummary: {
            /** Exception Id */
            exception_id: number;
            /** Type */
            type: string;
            /** Severity */
            severity: string;
            /** Status */
            status: string;
            /** Assignee */
            assignee?: string | null;
            /** Sla Due At */
            sla_due_at?: string | null;
            /** Sla Overdue Seconds */
            sla_overdue_seconds?: number | null;
        };
        /**
         * QueueItem
         * @description One queue row: invoice denormalized read model + latest run/exception.
         */
        QueueItem: {
            /** Invoice Id */
            invoice_id: number;
            /** Invoice Number */
            invoice_number?: string | null;
            /** Status */
            status: string;
            /** Vendor Id */
            vendor_id?: number | null;
            /** Currency */
            currency?: string | null;
            /** Amount Total */
            amount_total?: string | null;
            /** Issue Date */
            issue_date?: string | null;
            /** Created At */
            created_at: string;
            run?: components["schemas"]["QueueRunSummary"] | null;
            exception?: components["schemas"]["QueueExceptionSummary"] | null;
        };
        /** QueuePage */
        QueuePage: {
            /** Items */
            items: components["schemas"]["QueueItem"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** QueueRunSummary */
        QueueRunSummary: {
            /** Run Id */
            run_id: number;
            /** Route */
            route: string | null;
            /** Status */
            status: string;
            /** Confidence */
            confidence?: number | null;
        };
        /**
         * RunTrace
         * @description GET /v1/runs/{run_id}/trace — the ordered node timeline.
         */
        RunTrace: {
            /** Run Id */
            run_id: number;
            /** Invoice Id */
            invoice_id: number;
            /** Status */
            status: string;
            /** Route */
            route: string | null;
            /** Confidence */
            confidence: number | null;
            /** Graph Version */
            graph_version: string;
            /** Node Trace */
            node_trace?: string[];
            /** Timeline */
            timeline?: components["schemas"]["TraceEvent"][];
        };
        /** TraceEvent */
        TraceEvent: {
            /** Seq */
            seq: number;
            /** Actor Type */
            actor_type: string;
            /** Actor Id */
            actor_id: string | null;
            /** Event */
            event: string;
            /** Payload */
            payload: {
                [key: string]: unknown;
            };
            /** Created At */
            created_at: string;
            /** Versions */
            versions?: {
                [key: string]: unknown;
            } | null;
            /** Policy Version */
            policy_version?: string | null;
            /** Prompt Template Version */
            prompt_template_version?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    readyz_readyz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    list_invoices_v1_invoices_get: {
        parameters: {
            query?: {
                status?: string | null;
                route?: string | null;
                exception_type?: string | null;
                severity?: string | null;
                assignee?: string | null;
                vendor_id?: number | null;
                sort?: string;
                order?: string;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueuePage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ingest_invoice_v1_invoices_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_ingest_invoice_v1_invoices_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvoiceAccepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    invoice_detail_v1_invoices__invoice_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                invoice_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvoiceDetailAggregate"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    email_webhook_v1_invoices_email_webhook_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmailWebhookPayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvoiceAccepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    decide_exception_v1_exceptions__exception_id__decision_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                exception_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DecisionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DecisionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_trace_v1_runs__run_id__trace_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunTrace"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    invoice_provenance_v1_invoices__invoice_id__provenance_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                invoice_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProvenancePackage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
