"""0001 initial schema — full data model (ARCHITECTURE §6)

Revision ID: 822d4351d71a
Revises:
Create Date: 2026-08-27 19:39:32.694040

"""

from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "822d4351d71a"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "vendors",
        sa.Column("vendor_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("tax_id", sa.String(length=64), nullable=True),
        sa.Column("bank_details", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("risk_flags", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("vendor_id"),
    )
    op.create_table(
        "purchase_orders",
        sa.Column("po_id", sa.Integer(), nullable=False),
        sa.Column("po_number", sa.String(length=64), nullable=False),
        sa.Column("vendor_id", sa.Integer(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("lines", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("ordered_at", sa.Date(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["vendor_id"],
            ["vendors.vendor_id"],
        ),
        sa.PrimaryKeyConstraint("po_id"),
        sa.UniqueConstraint("po_number"),
    )
    op.create_table(
        "goods_receipts",
        sa.Column("gr_id", sa.Integer(), nullable=False),
        sa.Column("gr_number", sa.String(length=64), nullable=False),
        sa.Column("po_id", sa.Integer(), nullable=False),
        sa.Column("received_qty", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("received_at", sa.Date(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["po_id"],
            ["purchase_orders.po_id"],
        ),
        sa.PrimaryKeyConstraint("gr_id"),
        sa.UniqueConstraint("gr_number"),
    )
    op.create_table(
        "invoices",
        sa.Column("invoice_id", sa.Integer(), nullable=False),
        sa.Column("invoice_number", sa.String(length=64), nullable=True),
        sa.Column("vendor_id", sa.Integer(), nullable=True),
        sa.Column("po_id", sa.Integer(), nullable=True),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("doc_ref", sa.Text(), nullable=True),
        sa.Column("quality_tier", sa.String(length=1), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=True),
        sa.Column("amount_total", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("tax_total", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("issue_date", sa.Date(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
        sa.ForeignKeyConstraint(
            ["po_id"],
            ["purchase_orders.po_id"],
        ),
        sa.ForeignKeyConstraint(
            ["vendor_id"],
            ["vendors.vendor_id"],
        ),
        sa.PrimaryKeyConstraint("invoice_id"),
        sa.UniqueConstraint("content_hash"),
    )
    op.create_index("ix_invoices_status", "invoices", ["status"], unique=False)
    op.create_index("ix_invoices_vendor", "invoices", ["vendor_id"], unique=False)
    op.create_table(
        "invoice_lines",
        sa.Column("line_id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("invoice_id", sa.Integer(), nullable=False),
        sa.Column("line_no", sa.String(length=16), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("qty", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("uom", sa.String(length=16), nullable=True),
        sa.Column("unit_price", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column("tax_code", sa.String(length=32), nullable=True),
        sa.Column("line_total", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.ForeignKeyConstraint(["invoice_id"], ["invoices.invoice_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("line_id"),
        sa.UniqueConstraint("invoice_id", "line_no", name="uq_invoice_line_no"),
    )
    op.create_index(
        op.f("ix_invoice_lines_invoice_id"), "invoice_lines", ["invoice_id"], unique=False
    )
    op.create_table(
        "runs",
        sa.Column("run_id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("invoice_id", sa.Integer(), nullable=False),
        sa.Column("graph_version", sa.String(length=32), nullable=False),
        sa.Column("model_versions", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("route", sa.String(length=16), nullable=True),
        sa.Column("confidence", sa.Numeric(precision=6, scale=5), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["invoice_id"],
            ["invoices.invoice_id"],
        ),
        sa.PrimaryKeyConstraint("run_id"),
    )
    op.create_index(op.f("ix_runs_invoice_id"), "runs", ["invoice_id"], unique=False)
    op.create_table(
        "checkpoints",
        sa.Column("cp_id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("run_id", sa.BigInteger(), nullable=False),
        sa.Column("node", sa.String(length=64), nullable=False),
        sa.Column("state_snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["runs.run_id"],
        ),
        sa.PrimaryKeyConstraint("cp_id"),
    )
    op.create_index(op.f("ix_checkpoints_run_id"), "checkpoints", ["run_id"], unique=False)
    op.create_table(
        "exceptions",
        sa.Column("exception_id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("invoice_id", sa.Integer(), nullable=False),
        sa.Column("run_id", sa.BigInteger(), nullable=True),
        sa.Column("type", sa.String(length=32), nullable=False),
        sa.Column("severity", sa.String(length=16), nullable=False),
        sa.Column("evidence", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("recommendation", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("assignee", sa.String(length=128), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("sla_due_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["invoice_id"],
            ["invoices.invoice_id"],
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["runs.run_id"],
        ),
        sa.PrimaryKeyConstraint("exception_id"),
    )
    op.create_index(op.f("ix_exceptions_invoice_id"), "exceptions", ["invoice_id"], unique=False)
    op.create_table(
        "ledger",
        sa.Column("entry_id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("run_id", sa.BigInteger(), nullable=True),
        sa.Column("invoice_id", sa.Integer(), nullable=True),
        sa.Column("seq", sa.BigInteger(), nullable=False),
        sa.Column("actor_type", sa.String(length=16), nullable=False),
        sa.Column("actor_id", sa.String(length=128), nullable=True),
        sa.Column("event", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("model_versions", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("policy_version", sa.String(length=32), nullable=True),
        sa.Column("prompt_template_version", sa.String(length=32), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["invoice_id"],
            ["invoices.invoice_id"],
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["runs.run_id"],
        ),
        sa.PrimaryKeyConstraint("entry_id"),
        sa.UniqueConstraint("run_id", "seq", name="uq_ledger_run_seq"),
    )
    op.create_index(op.f("ix_ledger_invoice_id"), "ledger", ["invoice_id"], unique=False)
    op.create_index(op.f("ix_ledger_run_id"), "ledger", ["run_id"], unique=False)
    # HNSW for near-duplicate similarity search (choice recorded in models.py)
    op.execute(
        "CREATE INDEX ix_invoices_embedding ON invoices USING hnsw (embedding vector_cosine_ops)"
    )
    op.create_table(
        "decisions",
        sa.Column("decision_id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("exception_id", sa.BigInteger(), nullable=False),
        sa.Column("actor_user", sa.String(length=128), nullable=False),
        sa.Column("action", sa.String(length=32), nullable=False),
        sa.Column("rationale", sa.Text(), nullable=False),
        sa.Column("reason_code", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["exception_id"],
            ["exceptions.exception_id"],
        ),
        sa.PrimaryKeyConstraint("decision_id"),
    )
    op.create_index(op.f("ix_decisions_exception_id"), "decisions", ["exception_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # NOTE: the `vector` extension is left installed on downgrade (shared object).
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_decisions_exception_id"), table_name="decisions")
    op.drop_table("decisions")
    op.drop_index(op.f("ix_ledger_run_id"), table_name="ledger")
    op.drop_table("ledger")
    op.drop_index(op.f("ix_exceptions_invoice_id"), table_name="exceptions")
    op.drop_table("exceptions")
    op.drop_index(op.f("ix_checkpoints_run_id"), table_name="checkpoints")
    op.drop_table("checkpoints")
    op.drop_index(op.f("ix_runs_invoice_id"), table_name="runs")
    op.drop_table("runs")
    op.drop_index(op.f("ix_invoice_lines_invoice_id"), table_name="invoice_lines")
    op.drop_table("invoice_lines")
    op.drop_index("ix_invoices_vendor", table_name="invoices")
    op.drop_index("ix_invoices_status", table_name="invoices")
    op.drop_table("invoices")
    op.drop_table("goods_receipts")
    op.drop_table("purchase_orders")
    op.drop_table("vendors")
    # ### end Alembic commands ###
